
rollout: true

test_status_code: "200"

image:
  repository: docker.io/danielinclouds/go-status-code
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 8080
